Add credentials for telemetry
algorand/conduit pull request #144
Opened 2023-08-23 20:16 UTC by algochoi

## Summary

Adds telemetry credentials for our Opensearch dev cluster.

## Test Plan

Push telemetry events on startup on local conduit instance.

2023-08-24 14:47 UTC, tzaffi approved these changes

2023-08-28 20:24 UTC, winder commented on pkg/cli/internal/initialize/conduit.yml.example
> +    # password: "ratchet-tahiti-hunker-plebs-hamburg-wiretap-aplomb-mongoose-roomful"
Could you move this next to `metrics` so that all the plugins are configured at the end?

2023-09-01 16:16 UTC, winder requested changes
Could you move the defaults into the code? That way they can be updated with a software update rather than going stale if we want to change them in the future.

2023-09-05 13:34 UTC, algochoi commented
> Could you move the defaults into the code? That way they can be updated with a software update rather than going stale if we want to change them in the future.

That makes sense since we will likely change the URI some time in the future. But moving the defaults in the code could make it harder for users to set their custom telemetry endpoints (changing source code and recompiling the binary seems a bit more cumbersome). Is this an okay tradeoff here?

2025-09-03 14:48 UTC, closed without merging